#!/usr/bin/env python3
"""从 knowledge/insights/<phase>/*.yaml 自动生成 knowledge/insights/INDEX.yaml。

INDEX 是 insights 库的检索入口（解决 T-001：死库无检索路径）：
测试/规划时加载本索引，按 phase 整段浏览已有 approach，命中后再拉取对应 <ID>.yaml 全文。

用法：  python3 tools/build_insights_index.py        # 生成/刷新 INDEX
       python3 tools/build_insights_index.py --check # 只校验 INDEX 是否最新（CI 用，不写文件）
"""
import os, sys, re, yaml

ROOT = os.path.join(os.path.dirname(__file__), "..", "knowledge", "insights")
ROOT = os.path.normpath(ROOT)
INDEX = os.path.join(ROOT, "INDEX.yaml")
# phase 展示顺序（按当前规模降序，新 phase 追加在后）
PHASE_ORDER = ["authz", "auth", "chain", "input", "logic", "recon", "supply-chain"]

HEADER = (
    "# AUTO-GENERATED by tools/build_insights_index.py —— 请勿手改。\n"
    "# 用途：测试/规划时加载本索引，按 phase 整段浏览已有“打法(approach)”，命中后再拉取 <phase>/<ID>.yaml 全文。\n"
    "# 检索铁律：按 phase 整段过一遍，不可纯关键字匹配（见 README C2）。\n"
)


def one_line(s, limit=200):
    s = re.sub(r"\s+", " ", str(s)).strip()
    return s if len(s) <= limit else s[: limit - 1] + "…"


def load_all():
    entries = []
    for r, _, fs in os.walk(ROOT):
        for f in fs:
            if not f.endswith(".yaml") or f in ("articles.yaml", "INDEX.yaml"):
                continue
            p = os.path.join(r, f)
            d = yaml.safe_load(open(p, encoding="utf-8"))
            if not isinstance(d, dict):
                continue
            entries.append({
                "id": d.get("id") or os.path.splitext(f)[0],
                "phase": d.get("phase") or os.path.basename(os.path.dirname(p)),
                "approach": one_line(d.get("approach") or d.get("vuln_root") or ""),
                "also_phases": d.get("also_phases") or [],
            })
    return entries


def build(entries):
    by_phase = {}
    for e in entries:
        by_phase.setdefault(e["phase"], []).append(e)
    phases_out = {}
    for ph in PHASE_ORDER + sorted(p for p in by_phase if p not in PHASE_ORDER):
        if ph not in by_phase:
            continue
        phases_out[ph] = {e["id"]: e["approach"] for e in sorted(by_phase[ph], key=lambda x: x["id"])}
    cross = {e["id"]: e["also_phases"] for e in sorted(entries, key=lambda x: x["id"]) if e["also_phases"]}
    body = {
        "version": "1.0",
        "generated_from": "knowledge/insights/",
        "total": len(entries),
        "by_phase": {ph: len(v) for ph, v in phases_out.items()},
        "phases": phases_out,
    }
    if cross:
        body["cross_phase"] = cross
    return HEADER + yaml.dump(body, allow_unicode=True, sort_keys=False, width=10**6)


def main():
    entries = load_all()
    text = build(entries)
    if "--check" in sys.argv:
        cur = open(INDEX, encoding="utf-8").read() if os.path.exists(INDEX) else ""
        if cur != text:
            print("✗ INDEX.yaml 已过期，请运行: python3 tools/build_insights_index.py", file=sys.stderr)
            sys.exit(1)
        print(f"✓ INDEX.yaml 最新（{len(entries)} 条）")
        return
    open(INDEX, "w", encoding="utf-8").write(text)
    print(f"✓ 写入 {INDEX}：{len(entries)} 条 insight")


if __name__ == "__main__":
    main()
